// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyoWTaonZ8NzorQN3R3tlUR9LJGBhY11Y',
    appId: '1:291496564762:android:1e8c9e540b98e4818859a3',
    messagingSenderId: '291496564762',
    projectId: 'food-delivery-dbestech',
    databaseURL: 'https://food-delivery-dbestech-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-dbestech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BOmsAt2xhYXPwCSjA66vs-uxBOFuBP4',
    appId: '1:291496564762:ios:c6c62b9c4a3e88b38859a3',
    messagingSenderId: '291496564762',
    projectId: 'food-delivery-dbestech',
    databaseURL: 'https://food-delivery-dbestech-default-rtdb.firebaseio.com',
    storageBucket: 'food-delivery-dbestech.appspot.com',
    iosClientId: '291496564762-86ci5lksrc02fpf1h8shskt536u9svqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryDbestech',
  );
}
